-- ==========================================
-- 1. Create Services Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.services (
    id bigint generated by default as identity primary key,
    name text not null,
    price integer not null default 0,
    description text,
    image_url text,
    is_redeemable boolean default false,
    points_required integer default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for services
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;

-- Allow read access to all users
CREATE POLICY "Allow public read access on services" 
    ON public.services FOR SELECT 
    USING (true);

-- Allow all operations for authenticated users (admins)
CREATE POLICY "Allow authenticated full access on services" 
    ON public.services FOR ALL 
    TO authenticated 
    USING (true)
    WITH CHECK (true);

-- Insert initial dummy data based on previous hardcoded values
INSERT INTO public.services (name, price, description, is_redeemable, points_required)
VALUES 
    ('Mid Fade', 25000, 'A high-contrast style featuring a sharp fade on the sides and back.', false, 0),
    ('Comma Hair', 25000, 'A medium-length style with wavy hair, parted slightly off-center.', false, 0),
    ('Buzzcut', 25000, 'A very short style all around.', false, 0),
    ('Two Block', 25000, 'Longer top with very short sides.', false, 0)
ON CONFLICT DO NOTHING;


-- ==========================================
-- 2. Create Barbers Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.barbers (
    id bigint generated by default as identity primary key,
    name text not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS for barbers
ALTER TABLE public.barbers ENABLE ROW LEVEL SECURITY;

-- Allow read access to all users
CREATE POLICY "Allow public read access on barbers" 
    ON public.barbers FOR SELECT 
    USING (true);

-- Allow all operations for authenticated users (admins)
CREATE POLICY "Allow authenticated full access on barbers" 
    ON public.barbers FOR ALL 
    TO authenticated 
    USING (true)
    WITH CHECK (true);

-- Insert initial dummy data based on previous hardcoded values
INSERT INTO public.barbers (name, is_active)
VALUES 
    ('Ade', true),
    ('Eril', true)
ON CONFLICT DO NOTHING;


-- ==========================================
-- 3. Modify Products Table
-- ==========================================
-- Add redeemability columns if they don't exist
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS is_redeemable boolean default false;
ALTER TABLE public.products ADD COLUMN IF NOT EXISTS points_required integer default 0;

-- ==========================================
-- 4. Modify App Settings Table
-- ==========================================
-- We will keep the default table but drop the discount_per_point in theory, however SQLite/Postgres sometimes handles DROP COLUMN weirdly when dealing with data, so dropping is safer if explicit.
ALTER TABLE public.app_settings DROP COLUMN IF EXISTS discount_per_point;
