-- ==========================================
-- Create Gallery Images Table
-- ==========================================
CREATE TABLE IF NOT EXISTS public.gallery_images (
    id bigint generated by default as identity primary key,
    title text not null,
    category text,
    image_url text not null,
    is_active boolean default true,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable RLS
ALTER TABLE public.gallery_images ENABLE ROW LEVEL SECURITY;

-- Allow read access to all users
CREATE POLICY "Allow public read access on gallery_images" 
    ON public.gallery_images FOR SELECT 
    USING (true);

-- Allow all operations for authenticated users (admins)
CREATE POLICY "Allow authenticated full access on gallery_images" 
    ON public.gallery_images FOR ALL 
    TO authenticated 
    USING (true)
    WITH CHECK (true);
