"""
import_voucher_eligible.py
=========================
Converts the eligible_voucher_mahasiswa.xlsx into a clean SQL INSERT file.
Run this ONCE to generate the SQL, then paste it into Supabase SQL Editor.

Requirements:
    pip install openpyxl

Usage:
    python docs/import_voucher_eligible.py

Output:
    docs/insert_eligible_users.sql  (generated, then run in Supabase)
"""

import openpyxl
import os
import re

# ---- CONFIG ----
EXCEL_FILE   = os.path.join(os.path.dirname(__file__), 'eligible_voucher_mahasiswa.xlsx')
OUTPUT_FILE  = os.path.join(os.path.dirname(__file__), 'insert_eligible_users.sql')
PROGRAM_ID   = 'sg_unila_2026'
# ----------------

def normalize_phone(raw):
    """Normalize Indonesian phone numbers to 08xx format."""
    if not raw:
        return None
    phone = re.sub(r'[^0-9]', '', str(raw).strip())
    if phone.startswith('62'):
        phone = '0' + phone[2:]
    if not phone.startswith('0'):
        phone = '0' + phone
    return phone

def escape_sql(value):
    """Escape a string for safe SQL insertion."""
    if value is None:
        return 'NULL'
    return "'" + str(value).replace("'", "''").strip() + "'"

def main():
    wb = openpyxl.load_workbook(EXCEL_FILE)
    ws = wb.active

    rows = list(ws.iter_rows(min_row=2, values_only=True))  # Skip header
    
    # Deduplicate: if same NPM appears multiple times, keep the LAST entry
    # (most recent submission wins)
    seen_npms = {}
    skipped = 0
    for row in rows:
        timestamp, email, name, npm_raw, phone_raw = row
        if npm_raw is None:
            skipped += 1
            continue
        try:
            # Handle both float (2414181045.0) and string ('251 3033063') NPMs
            npm_clean = str(npm_raw).replace(' ', '').strip()
            npm = str(int(float(npm_clean)))
            if len(npm) < 8:  # Sanity check: skip clearly invalid NPMs
                print(f'  [WARN] Skipping invalid NPM "{npm_raw}" (too short)')
                skipped += 1
                continue
        except (ValueError, TypeError):
            print(f'  [WARN] Skipping unparseable NPM: "{npm_raw}"')
            skipped += 1
            continue
        seen_npms[npm] = {
            'email': str(email).strip() if email else None,
            'name':  str(name).strip() if name else None,
            'phone': normalize_phone(phone_raw),
        }
    
    print(f"Total rows in Excel: {len(rows)}")
    print(f"Skipped (bad/missing NPM): {skipped}")
    print(f"Unique NPMs after deduplication: {len(seen_npms)}")
    print(f"Duplicates removed: {len(rows) - skipped - len(seen_npms)}")
    print(f"Generating SQL -> {OUTPUT_FILE}")

    lines = [
        "-- Auto-generated by import_voucher_eligible.py",
        f"-- Program: {PROGRAM_ID}",
        f"-- Total records: {len(seen_npms)}",
        "--",
        "-- INSTRUCTIONS: Paste this into Supabase SQL Editor and click Run.",
        "",
        "INSERT INTO program_eligible_users",
        "    (program_id, identifier, email, name, phone_number)",
        "VALUES",
    ]

    entries = []
    for npm, data in seen_npms.items():
        email_sql = escape_sql(data['email'])
        name_sql  = escape_sql(data['name'])
        phone_sql = escape_sql(data['phone'])
        entries.append(
            f"    ({escape_sql(PROGRAM_ID)}, {escape_sql(npm)}, {email_sql}, {name_sql}, {phone_sql})"
        )

    lines.append(",\n".join(entries))
    lines.append("ON CONFLICT (program_id, identifier) DO UPDATE SET")
    lines.append("    email        = EXCLUDED.email,")
    lines.append("    name         = EXCLUDED.name,")
    lines.append("    phone_number = EXCLUDED.phone_number;")
    lines.append("")
    lines.append(f"-- Done. {len(seen_npms)} records inserted/updated.")

    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        f.write("\n".join(lines))

    print(f"\n[OK] Done! SQL file generated: {OUTPUT_FILE}")
    print("   Next step: Open Supabase SQL Editor and paste/run that file.")

if __name__ == '__main__':
    main()
