-- ============================================================
-- STORE SETTINGS & OPERATING HOURS SCHEMA
-- Auro Barbershop | barberpage project
-- Run this in Supabase SQL Editor to initialize settings
-- ============================================================

-- 1. Create settings table if not exists
CREATE TABLE IF NOT EXISTS public.settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    opening_hour TEXT NOT NULL DEFAULT '09:00',
    closing_hour TEXT NOT NULL DEFAULT '21:00',
    daily_hours JSONB NOT NULL DEFAULT '[
        {"dayOfWeek": 1, "dayName": "Senin", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 2, "dayName": "Selasa", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 3, "dayName": "Rabu", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 4, "dayName": "Kamis", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 5, "dayName": "Jumat", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 6, "dayName": "Sabtu", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 0, "dayName": "Minggu", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"}
    ]'::jsonb,
    updated_at TIMESTAMPTZ DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;

-- 3. Drop existing policies if any to avoid conflicts
DROP POLICY IF EXISTS "Allow public read on settings" ON public.settings;
DROP POLICY IF EXISTS "Allow authenticated full access on settings" ON public.settings;

-- 4. Create RLS Policies
-- Allow anyone (including anonymous customers booking online) to read store hours
CREATE POLICY "Allow public read on settings"
    ON public.settings
    FOR SELECT
    USING (true);

-- Allow authenticated admins to insert/update settings
CREATE POLICY "Allow authenticated full access on settings"
    ON public.settings
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);

-- 5. Seed initial row if table is empty
INSERT INTO public.settings (id, store_name, opening_hour, closing_hour, daily_hours)
VALUES (
    1,
    'Auro Barbershop',
    '09:00',
    '21:00',
    '[
        {"dayOfWeek": 1, "dayName": "Senin", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 2, "dayName": "Selasa", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 3, "dayName": "Rabu", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 4, "dayName": "Kamis", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 5, "dayName": "Jumat", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 6, "dayName": "Sabtu", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"},
        {"dayOfWeek": 0, "dayName": "Minggu", "isHoliday": false, "openingHour": "09:00", "closingHour": "21:00"}
    ]'::jsonb
)
ON CONFLICT (id) DO UPDATE SET
    store_name = COALESCE(settings.store_name, EXCLUDED.store_name),
    opening_hour = EXCLUDED.opening_hour,
    closing_hour = EXCLUDED.closing_hour,
    daily_hours = EXCLUDED.daily_hours;
